# Generated by Django 4.2.10 on 2025-04-06 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_preference', models.CharField(choices=[('all', 'All Notifications'), ('appointments_only', 'Appointments Only'), ('important_only', 'Important Only'), ('none', 'None')], default='all', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('auto_confirm_appointments', models.BooleanField(default=False)),
                ('calendar_view_preference', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='week', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Settings',
                'verbose_name_plural': 'Staff Settings',
            },
        ),
    ]
