# Generated by Django 5.2 on 2025-04-05 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberian_common', '0002_smsnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotification',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_created', 'Appointment Created'), ('appointment_updated', 'Appointment Updated'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_reminder', 'Appointment Reminder'), ('manual', 'Manual Message')], max_length=50),
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
