# Generated by Django 4.2.10 on 2025-04-06 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barberian_common', '0004_remove_notificationpreference_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service_media/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='barberian_common.service')),
            ],
            options={
                'verbose_name': 'Service Media',
                'verbose_name_plural': 'Service Media',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
